export const ROLES = {
  ADMIN:      'ADMIN',
  ACCOUNTANT: 'ACCOUNTANT',
  USER:       'USER',
}

export const ALL_ROLES            = [ROLES.ADMIN, ROLES.ACCOUNTANT, ROLES.USER]
export const CAN_MANAGE_USERS     = [ROLES.ADMIN]
export const CAN_MANAGE_MASTER    = [ROLES.ADMIN, ROLES.ACCOUNTANT]
export const CAN_MANAGE_TRANSACTIONS = [ROLES.ADMIN, ROLES.ACCOUNTANT]
export const CAN_MANAGE_INVOICES  = [ROLES.ADMIN, ROLES.ACCOUNTANT]
export const CAN_MANAGE_PAYMENTS  = [ROLES.ADMIN, ROLES.ACCOUNTANT]
export const CAN_VIEW_REPORTS     = [ROLES.ADMIN, ROLES.ACCOUNTANT]
